EWPP-1062: Handle group property in user data.
openeuropa/oe_authentication pull request #131
Opened 2021-06-09 11:18 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-06-11 06:43 UTC, brummbar requested changes
I was happy about the PR, but then I noticed the double quotes...
![image](https://user-images.githubusercontent.com/8488617/121642629-136e5a80-ca91-11eb-9243-9e61c84371af.png)

2021-07-27 14:44 UTC, brummbar approved these changes

2021-07-27 14:58 UTC, brummbar approved these changes

2021-07-28 06:35 UTC, imanoleguskiza approved these changes

2021-07-28 11:58 UTC, merged