OEL-3187: Upgrade to Drupal 11
openeuropa/oe_authentication pull request #190
Opened 2024-10-16 07:31 UTC by drishu

## OEL-3187

### Description

Upgrade to Drupal 11.

### Change log

- Changed: CAS api usage
- Removed: D9, D10 compatibility
- Security: Upgraded static code analysis

2024-10-25 12:21 UTC, brummbar commented on .drone.yml
>      command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
Set this command for improved performances:
```
command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3 --skip-log-bin --innodb-flush-log-at-trx-commit=2 --innodb-read-io-threads=16 --innodb-write-io-threads=16
```

2024-10-30 09:43 UTC, nagyad commented on docker-compose.yml
>  version: '2'
Let's remove this as well.

2024-10-30 10:09 UTC, nagyad requested changes

2024-10-30 10:09 UTC, nagyad commented on .drone.yml
> +      PHP_VERSION: 8.3
This is not going to work! We need to keep support of D10 until June 2026. We can't force projects to go D11 all of a sudden. Also CAS 3.0 support D10, we should follow suit.

2024-11-13 16:23 UTC, drishu commented on .drone.yml
> +      - CORE_VERSION: 11
good question, for now 11.0 will be ok

2024-11-14 10:43 UTC, sergepavle submitted a review, later dismissed

2024-12-06 10:25 UTC, nagyad approved these changes

2024-12-06 10:36 UTC, sergepavle submitted a review, later dismissed

2024-12-06 10:50 UTC, brummbar submitted a review, later dismissed

2024-12-06 10:50 UTC, brummbar commented on composer.json
> +        "openeuropa/code-review-drupal": "dev-EWPP-4665",
This needs to point to a release.

2024-12-07 16:24 UTC, drishu commented on composer.json
>          "openeuropa/task-runner-drupal-project-symlink": "^1.0-beta6",
we still need to sort out the task runner:
- this merged https://github.com/openeuropa/task-runner/pull/173/files
- this sorted out https://github.com/openeuropa/task-runner-drupal-project-symlink/blob/1.x/composer.json#L11 (wasn't pointing to a release)
- and then some releases for these 2 packages.

2024-12-16 13:58 UTC, drishu commented on composer.json
>          "openeuropa/task-runner-drupal-project-symlink": "^1.0-beta6",
done

2024-12-17 15:16 UTC, sergepavle approved these changes

2024-12-18 09:02 UTC, nagyad approved these changes

2024-12-18 14:53 UTC, merged